repos:

# yapf
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
        args: [--style=.style.yapf, --recursive, --diff, .]

# flake8
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: [--config=.flake8]

# mypy
# For some reason, pre-commit mypy doesn't like our folder structure raising errors such as:
# Duplicate module named 'dockstring'
# Disabling for now.
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.812'  # pick a git hash / tag to point to
#    hooks:
#    -   id: mypy
#        args: [--config=.mypy.ini, ./dockstring]
